### ISSUE TITLE
DataCombine/FindReplace errors

### ISSUE THREAD

**Issue by TylerSchnoebelen** [lyons7/emojidictionary#1]
Thanks for this! 

I have been trying to sort out why I can't get the FindReplace piece to work--I have done the iconv work and confirmed the class() of my tweet text (despite the error it is DEFINITELY "character", so are the columns in your spreadsheets), but I keep getting this error:
```
Error: text is not a character string or factor. Please convert to a character string or factor and then rerun.
In addition: Warning message:
In if (!(class(data[, Var]) %in% c("character", "factor"))) { :
  the condition has length > 1 and only the first element will be used
```
I don't suppose you've seen this? Google searches haven't turned up anything particularly useful and it's blocking me from trying out your cool mapping.

**Comment by lyons7** [comment]
Hi Tyler!

Would you mind sending along a subset of your data and the exact string of
code you are using? I think I might be able to troubleshoot a little bit
better with that -- hopefully we'll be able to fix this issue!

Kate

**Comment by MikoBie** [comment]
This is probably because you use `dplyr` and your data frame is not a basic data frame but `dplyr` data frame tibble. If you just convert it by using `as.data.frame()` to a basic one it should work.
